[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "apikey.crypt"
tries = 5
user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"

[asdf-vm]
source = "github"
github = "asdf-vm/asdf"
use_latest_release = true
prefix = "v"

[auth]
source = "github"
github = "xsy420/auth"
use_latest_tag = true
prefix = "v"

[battery-monitor]
source = "github"
github = "xsy420/battery-monitor"
use_latest_release = true
prefix = "v"

[bilibili]
source = "github"
github = "msojocs/bilibili-linux"
use_latest_release = true
prefix = "v"

[baidunetdisk-bin]
source = "aur"

[cherry-studio-bin]
source = "github"
github = "cherryHQ/cherry-studio"
use_latest_release = true
prefix = "v"

[dmg2img]
source = "aur"

[downgrade]
source = "github"
github = "archlinux-downgrade/downgrade"
use_latest_release = true
prefix = "v"

[duckdb]
source = "github"
github = "duckdb/duckdb"
use_latest_release = true
prefix = "v"

[euporie]
source = "github"
github = "joouha/euporie"
use_max_tag = true
prefix = "v"

[fzf-make]
source = "github"
github = "kyu08/fzf-make"
use_latest_release = true
prefix = "v"

[google-chrome]
source = "apt"
mirror = "https://dl.google.com/linux/chrome/deb/"
pkg = "google-chrome-stable"
suite = "stable"
repo = "main"
strip_release = true

[greenclip]
source = "hackage"

[harlequin]
source = "github"
github = "tconbeer/harlequin"
use_latest_release = true
prefix = "v"

[harlequin-mysql]
source = "github"
github = "tconbeer/harlequin-mysql"
use_latest_release = true
prefix = "v"

[haskell-semigroups]
source = "hackage"
hackage = "semigroups"

[haskell-wordexp]
source = "hackage"
hackage = "wordexp"

[lazydocker]
source = "github"
github = "jesseduffield/lazydocker"
use_latest_release = true
prefix = "v"

[libcyaml]
source = "github"
github = "tlsa/libcyaml"
use_latest_release = true
prefix = "v"

[libxls]
source = "github"
github = "libxls/libxls"
use_latest_release = true
prefix = "v"

[linuxqq-nt-bwrap]
source = "regex"
url = "https://cdn-go.cn/qq-web/im.qq.com_new/latest/rainbow/linuxConfig.js"
regex = "QQ_(.*)_amd64_01.deb"

[mysql]
source = "regex"
url = "https://dev.mysql.com/downloads/mysql/"
regex = "MySQL Community Server ([0-9\\.]+) Innovation"
user_agent = "curl/8.12.1"

[navicat17-premium-cs]
source = "regex"
url = "https://www.navicat.com/products/navicat-premium-release-note#L"
regex = "Navicat Premium \\(Linux\\) version (.*)</b>"

[pacfiles]
source = "github"
github = "lilydjwg/pacfiles"
use_latest_tag = true
prefix = "v"

[python-aenum]
source = "github"
github = "ethanfurman/aenum"
use_latest_tag = true
prefix = "v"

['python-backports.cached_property']
source = "github"
github = "penguinolog/backports.cached_property"
use_latest_release = true
prefix = "v"

[python-chafapy]
source = "github"
github = "guardkenzie/chafa.py"
use_latest_release = true
prefix = "v"

[python-flatlatex]
source = "github"
github = "jb-leger/flatlatex"
use_max_tag = true
prefix = "v"

[python-imageio-ffmpeg]
source = "github"
github = "imageio/imageio-ffmpeg"
use_latest_release = true
prefix = "v"

[python-img2unicode]
source = "github"
github = "matrach/img2unicode"
use_commit = true

[python-jupytext]
source = "github"
github = "mwouts/jupytext"
use_latest_release = true
prefix = "v"

[python-moviepy]
source = "github"
github = "Zulko/moviepy"
use_latest_release = true
prefix = "v"

[python-mtable]
source = "github"
github = "liuyug/mtable"
use_commit = true

[python-pandas-stubs]
source = "github"
github = "pandas-dev/pandas-stubs"
use_max_tag = true
prefix = "v"

[python-pathlib-abc]
source = "github"
github = "barneygale/pathlib-abc"
use_max_tag = true

[python-proglog]
source = "github"
github = "Edinburgh-Genome-Foundry/Proglog"
use_latest_release = true
prefix = "v"

[python-questionary]
source = "github"
github = "tmbo/questionary"
use_max_tag = true
prefix = "v"

[python-shandy-sqlfmt]
source = "pypi"
pypi = "shandy-sqlfmt"

[python-sixelcrop]
source = "pypi"
pypi = "sixelcrop"

[python-teimpy]
source = "github"
github = "ar90n/teimpy"
use_max_tag = true
prefix = "v"

[python-textual-fastdatatable]
source = "github"
github = "tconbeer/textual-fastdatatable"
use_latest_release = true
prefix = "v"

[python-textual-textarea]
source = "pypi"
pypi = "textual-textarea"

[python-timg]
source = "pypi"
pypi = "timg"

[python-universal_pathlib]
source = "github"
github = "fsspec/universal_pathlib"
use_latest_release = true
prefix = "v"

[reg]
source = "github"
github = "genuinetools/reg"
use_latest_release = true
prefix = "v"

[ruby-fusuma]
source = "gems"
gems = "fusuma"

[td-tui]
source = "github"
github = "voioo/td"
use_latest_release = true
prefix = "v"

[television]
source = "github"
github = "alexpasmantier/television"
use_latest_release = true
prefix = "v"

[typora]
source = "regex"
url = "https://www.typora.io/releases/stable.html"
regex = "typora_([0-9\\.]+)_amd64.deb"

[xwin]
source = "cratesio"

[yay]
source = "github"
github = "Jguer/yay"
use_latest_release = true
prefix = "v"
